<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 12px; color: #1f2937; margin: 0; padding: 30px; }
        table { width: 100%; border-collapse: collapse; }
        .header-table td { vertical-align: top; }
        .brand { font-size: 20px; font-weight: bold; color: #4338ca; }
        .muted { color: #6b7280; }
        .right { text-align: right; }
        .status { display: inline-block; padding: 3px 10px; border-radius: 10px; background: #fef3c7; color: #92400e; font-size: 11px; text-transform: capitalize; }
        .items-table { margin-top: 25px; }
        .items-table th { text-align: left; background: #f9fafb; padding: 8px 6px; font-size: 10px; text-transform: uppercase; color: #6b7280; border-bottom: 1px solid #e5e7eb; }
        .items-table td { padding: 8px 6px; border-bottom: 1px solid #f3f4f6; }
        .items-table tfoot td { border-top: 2px solid #d1d5db; border-bottom: none; font-weight: bold; padding-top: 10px; }
        .summary-table { margin-top: 20px; width: 60%; margin-left: auto; }
        .summary-table td { padding: 4px 6px; }
        .summary-table .total-row td { border-top: 1px solid #d1d5db; font-weight: bold; font-size: 13px; padding-top: 8px; }
        .footer { margin-top: 40px; font-size: 10px; color: #9ca3af; }
    </style>
</head>
<body>
    <table class="header-table">
        <tr>
            <td>
                <div class="brand">{{ $invoice->merchant->name }}</div>
                <div class="muted">{{ $invoice->merchant->email }}</div>
            </td>
            <td class="right">
                <div style="font-size: 16px; font-weight: bold;">{{ $invoice->invoice_number }}</div>
                <div class="muted">Issued {{ $invoice->issued_at->format('d M Y') }}</div>
                <div style="margin-top: 6px;"><span class="status">{{ $invoice->status->value }}</span></div>
            </td>
        </tr>
    </table>

    <table class="header-table" style="margin-top: 25px;">
        <tr>
            <td>
                <div class="muted">Billed to</div>
                <div style="font-weight: bold;">{{ $invoice->customer->name }}</div>
                <div class="muted">{{ $invoice->customer->email }}</div>
            </td>
            <td class="right">
                <div class="muted">Billing period</div>
                <div style="font-weight: bold;">{{ $invoice->period_start->format('d M Y') }} &ndash; {{ $invoice->period_end->format('d M Y') }}</div>
            </td>
        </tr>
    </table>

    <table class="items-table">
        <thead>
            <tr>
                <th>Description</th>
                <th>Type</th>
                <th>Period</th>
                <th class="right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($invoice->items as $item)
                <tr>
                    <td>{{ $item->description }}</td>
                    <td class="muted" style="text-transform: capitalize;">{{ str_replace('_', ' ', $item->type->value) }}</td>
                    <td class="muted">
                        @if ($item->period_start)
                            {{ $item->period_start->format('d M') }} &ndash; {{ $item->period_end->format('d M') }}
                        @else
                            &mdash;
                        @endif
                    </td>
                    <td class="right">{{ \App\Support\Money::format($item->amount_cents, $invoice->currency) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="right">Total</td>
                <td class="right">{{ \App\Support\Money::format($invoice->total_amount_cents, $invoice->currency) }}</td>
            </tr>
        </tfoot>
    </table>

    <table class="summary-table">
        <tr>
            <td class="muted">Base charges</td>
            <td class="right">{{ \App\Support\Money::format($invoice->base_amount_cents, $invoice->currency) }}</td>
        </tr>
        <tr>
            <td class="muted">Overage ({{ number_format($invoice->overage_units) }} units)</td>
            <td class="right">{{ \App\Support\Money::format($invoice->overage_amount_cents, $invoice->currency) }}</td>
        </tr>
        <tr class="total-row">
            <td>Total Due</td>
            <td class="right">{{ \App\Support\Money::format($invoice->total_amount_cents, $invoice->currency) }}</td>
        </tr>
    </table>

    <div class="footer">Generated by APIFlow &middot; {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
